<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:property name="base_length" value="0.6"/>
    <xacro:property name="base_width" value="0.6"/>
    <xacro:property name="base_height" value="0.3"/>
    <xacro:property name="link_length" value="0.6"/>
    <xacro:property name="link_width" value="0.1"/>
    <xacro:property name="link_height" value="0.05"/>
    <xacro:property name="link_3_radius" value="0.02"/>
    <xacro:property name="link_3_length" value="0.4"/>
    <xacro:property name="offset" value="0.05"/>

    <link name="base_footprint"/>

    <link name="base_link">
        <visual>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}"/>
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <material name="grey"/>
        </visual>
        <collision>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}"/>
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </collision>

        <xacro:box_inertia m="50" l="${base_length * 2}" w="${base_width*2}" h="${base_height}"
                            xyz="0 0 0" rpy="0 0 0"/>
    </link>

    <link name="link_1">
        <visual>
            <geometry>
                <box size="${link_length} ${link_width} ${link_height}"/>
            </geometry>
            <origin xyz="${-link_length/2 + offset} 0 0" rpy="0 0 0"/>
            <material name="blue"/>
        </visual>
        <collision>
            <geometry>
                <box size="${link_length} ${link_width} ${link_height}"/>
            </geometry>
            <origin xyz="${-link_length/2 + offset} 0 0" rpy="0 0 0"/>
        </collision>

        <xacro:box_inertia m="5" l="${2*link_length}" w="${2*base_width}" h="${base_height}"
                            xyz="${-link_length/2 + offset} 0 0" rpy="0 0 0"/>
    </link>

    <link name="link_2">
        <visual>
            <geometry>
                <box size="${link_length} ${link_width} ${link_height}"/>
            </geometry>
            <origin xyz="${-link_length/2 + offset} 0 ${link_height/2}" rpy="0 0 0"/>
            <material name="blue"/>
        </visual>

        <collision>
            <geometry>
                <box size="${link_length} ${link_width} ${link_height}"/>
            </geometry>
            <origin xyz="${-link_length/2 + offset} 0 ${link_height/2}" rpy="0 0 0"/>
        </collision>

        <xacro:box_inertia m="5" l="${2*link_length}" w="${2*base_width}" h="${base_height}"
                            xyz="${-link_length/2 + offset} 0 ${link_height/2}" rpy="0 0 0"/>
    </link>

    <link name="link_3">
        <visual>
            <geometry>
                <cylinder radius="${link_3_radius}" length="${link_3_length}"/>
            </geometry>
            <origin xyz="0 0 ${-link_3_length/2}" rpy="0 0 0"/>
            <material name="orange"/>
        </visual>

        <collision>
            <geometry>
                <cylinder radius="${link_3_radius}" length="${link_3_length}"/>
            </geometry>
            <origin xyz="0 0 ${-link_3_length/2}" rpy="0 0 0"/>
        </collision>

        <xacro:cylinder_inertia m="5" r="${2*link_3_radius}" l="${2*link_3_length}"
                            xyz="0 0 ${-link_3_length/2}" rpy="0 0 0"/>

    </link>

    <joint name="base_joint" type="fixed">
        <parent link="base_footprint"/>
        <child link="base_link"/>
        <origin xyz="0 0 ${base_height/2}" rpy="0 0 0"/>
    </joint>

    <joint name="joint_1" type="revolute">
        <parent link="base_link"/>
        <child link="link_1"/>
        <origin xyz="${-link_length/2 + offset} 0 ${(base_height + link_height)/2}" rpy="0 0 0"/>
        <axis xyz="0 0 1"/>
        <limit lower="${-pi/2}" upper="${pi/2}" effort="100" velocity="100"/>
        <dynamics friction="1000" damping="1000"/>

    </joint>

    
    <joint name="joint_2" type="revolute">
        <parent link="link_1"/>
        <child link="link_2"/>
        <origin xyz="${-link_length + offset} 0 ${link_height/2}" rpy="0 0 0"/>
        <axis xyz="0 0 1"/>
        <limit lower="${-pi/2}" upper="${pi/2}" effort="100" velocity="100"/>
        <dynamics friction="1000" damping="1000"/>
    </joint>

    <joint name="joint_3" type="prismatic">
        <parent link="link_2"/>
        <child link="link_3"/>
        <origin xyz="${-link_length + offset + link_3_radius*2} 0 0" rpy="0 0 0"/>
        <axis xyz="0 0 1"/>
        <limit lower="0" upper="0.4" effort="100" velocity="100"/>
        <dynamics friction="1000" damping="1000"/>
    </joint>

  

</robot>