<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:property name="base_length" value="0.6"/>
    <xacro:property name="base_width" value="0.6"/>
    <xacro:property name="base_height" value="0.3"/>
    <xacro:property name="link_length" value="0.6"/>
    <xacro:property name="link_width" value="0.1"/>
    <xacro:property name="link_height" value="0.05"/>
    <xacro:property name="link_3_radius" value="0.1"/>
    <xacro:property name="link_3_length" value="0.3"/>
    <xacro:property name="offset" value="0.05"/>

    <link name="base_footprint"/>

    <link name="base_link">
        <visual>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}"/>
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <material name="grey"/>
        </visual>
    </link>

    <link name="link_1">
        <visual>
            <geometry>
                <box size="${link_length} ${link_width} ${link_height}"/>
            </geometry>
            <origin xyz="${-link_length/2 + offset} 0 0" rpy="0 0 0"/>
            <material name="blue"/>
        </visual>
    </link>

    <link name="link_2">
        <visual>
            <geometry>
                <box size="${link_length} ${link_width} ${link_height}"/>
            </geometry>
            <origin xyz="${-link_length/2 + offset} 0 ${link_height/2}" rpy="0 0 0"/>
            <material name="orange"/>
        </visual>
    </link>

    

    <joint name="base_joint" type="fixed">
        <parent link="base_footprint"/>
        <child link="base_link"/>
        <origin xyz="0 0 ${base_height/2}" rpy="0 0 0"/>
    </joint>

    <joint name="joint_1" type="revolute">
        <parent link="base_link"/>
        <child link="link_1"/>
        <origin xyz="${-link_length/2 + offset} 0 ${(base_height + link_height)/2}" rpy="0 0 0"/>
        <axis xyz="0 0 1"/>
        <limit lower="${-pi/2}" upper="${pi/2}" effort="100" velocity="100"/>
        <dynamics friction="1000" damping="1000"/>

    </joint>

    
    <joint name="joint_2" type="revolute">
        <parent link="link_1"/>
        <child link="link_2"/>
        <origin xyz="${-link_length + offset} 0 ${link_height/2}" rpy="0 0 0"/>
        <axis xyz="0 0 1"/>
        <limit lower="${-pi/2}" upper="${pi/2}" effort="100" velocity="100"/>
        <dynamics friction="1000" damping="1000"/>
    </joint>


</robot>